version: '3.2'

services: 
    db:
        hostname: mysql
        image: mysql:5.7.31
        restart: always
        ports: 
            - 3307:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: smartpark
            MYSQL_USER: smartpark
            MYSQL_PASSWORD: smartpark
            MYSQL_DATABASE: smartpark
    app:
        hostname: app
        image : ksh24865/smartpark-app:0.1
        restart: always
        ports:
            - 8081:8081
        environment: 
            APP_SERVER: 0.0.0.0:8081
            DB_DRIVE: mysql
            DB_SERVER: db:3306
            DB_USER: smartpark
            DB_PASS: smartpark
            DB_DATABASE: smartpark
            TOPIC_NAME: sensor-data
        depends_on: 
            - db
        links:
            - db 