version: '3.2'

services:
    logic:
        hostname: logic
        image: ksh24865/smartpark-logic:0.0.1
        restart: always
        ports: 
            - 8082:8082
        environment: 
            LOGIC_SERVER: 0.0.0.0:8082
            LOGIC_LISTEN: logic:8082
            APP_SERVER: 0.0.0.0:8081
            KAFKA_BROKER: kafka:9092
            KAFKA_GROUP: logic1
            KAFKA_TOPIC: sensor-data
            ELASTIC_SERVER: elasticsearch:9200
    
